"""add roles and user_roles

Revision ID: c16ec8d9a594
Revises: 6f9a00f1a7e6
Create Date: 2026-01-30 04:23:47.056135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16ec8d9a594'
down_revision: Union[str, Sequence[str], None] = '6f9a00f1a7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "members",
    sa.Column("role_id", sa.Integer(), nullable=True)
     )
    op.create_foreign_key(None, 'members', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'role_id')
    # ### end Alembic commands ###
